# Used for local test only!!!
# 仅用于本地测试!!!
services:
  postgresql:
    image: 'bitnami/postgresql'
    environment:
      POSTGRESQL_PASSWORD: o46UyptJsJNxqr
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/bitnami/postgresql
  redis:
    image: 'bitnami/redis'
    environment:
      REDIS_PASSWORD: F5chYxP2mGtKqL9d7u8CMp
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local