[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
axum = { version = "0.7.9", features = ["macros"] }
deadpool-redis = { version = "0.18.0", features = ["serde"] }
dotenvy = "0.15.7"
futures = "0.3.31"
redis = { version = "0.27.6", features = ["tokio-comp"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["macros", "migrate", "postgres", "runtime-tokio"] }
thiserror = "2.0.8"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
utoipa = { version = "5.2.0", features = ["axum_extras", "openapi_extensions", "time"] }
utoipa-axum = "0.1.2"
utoipa-scalar = { version = "0.2.0", features = ["axum"] }
validator = { version = "0.19.0", features = ["derive"] }
